export const ADD_FILE = 'ADD_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const ADD_FILE_TO_COLLECTION = 'ADD_FILE_TO_COLLECTION';
export const REMOVE_FILE_FROM_COLLECTION = 'REMOVE_FILE_FROM_COLLECTION';
export const FILE_DATABASE_DIRECTORY = '_____DB_____';
