export const FOLDER_FILES_FETCH_REQUESTED = 'FOLDER_FILES_FETCH_REQUESTED';
export const FOLDER_FILES_FETCH_FAILED = 'FOLDER_FILES_FETCH_FAILED';
export const FOLDER_FILES_FETCH_SUCCEEDED = 'FOLDER_FILES_FETCH_SUCCEEDED';

export const SHARED_LINKS_REQUESTED = 'SHARED_LINKS_REQUESTED';
export const SHARED_LINKS_FETCH_SUCCEEDED = 'SHARED_LINKS_FETCH_SUCCEEDED';
export const SHARED_LINKS_FETCH_FAILED = 'SHARED_LINKS_FETCH_FAILED';
