export const FOLDER_FILES_FETCH_REQUESTED = 'FOLDER_FILES_FETCH_REQUESTED';
export const FOLDER_FILES_FETCH_FAILED = 'FOLDER_FILES_FETCH_FAILED';
export const FOLDER_FILES_FETCH_SUCCEEDED = 'FOLDER_FILES_FETCH_SUCCEEDED';
